#!/usr/bin/env bash
# Installs Nginx with the following configurations

apt-get -y update
apt-get -y install nginx

sudo sed -i 's/.*listen 80;/\tlisten 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart

echo "<html><body>Hello World!</body></html>" | sudo tee /var/www/html/index.html > /dev/null
sudo nginx -t

if [ $? -eq 0 ]; then
    sudo nginx -s reload
else
    echo "Nginx configuration test failed. Check nginx logs for more information."
fi

response=$(curl -s http://localhost)

if [[ "$response" == *Hello\ World!* ]]; then
    echo "Nginx is configured successfully."
else
    echo "Nginx configuration failed. Check nginx logs for more information."
fi
