#!/usr/bin/env bash
# Displays numbers from 1 to 100 in list format.
#   Displays "FizzBuzz" when the number is a multiple of 3 and 5.
#   Displays "Fizz" when the number is a multiple of 3.
#   Displays "Buzz" when the number is a multiple of 5.
#   Otherwise, displays the number.

count=1
while [ $count -ne 101 ]
do
    if [ $((count % 15)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((count % 3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $((count % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
	echo $count
    fi
    ((count++))
done
